### ISSUE TITLE
page nr

### ISSUE THREAD

**Issue by marcodemayda** [phi-math-website/phi-math-website#1]
Front page (and some other) always has 2 pages.
Front page should have none. Other pages should have (potentially) more.

**Comment by foxyseta** [comment]
> Front page should have none.

I agree! Will fix this when I have time.

> Other pages should have (potentially) more.

In paginations, the number of pages is computed as

$\lceil \frac{n}{p} \rceil = \lceil \frac{20}{10} \rceil = 2 $

where $n$ is the number of entries (in our case, we have 20 events), and $p$ is the maximum size a page can have. Hugo's default value is 10, but you can change it here, if you uncomment the code first: https://github.com/phi-math-website/phi-math-website/blob/efe9af04a81a2f20d1e50f2a37569302501b02ff/hugo.toml#L12

So as soon as you add the 21th event in the "Readings" category, a third page will be created (just tested this, even though that was the behavior people always expect).
